{% set name = "rt1" %}
{% set version = "2.0" %}
{% set sha256 = "e726c1a3b69da8809f07409e40f9510608749342edb2518954b96e076cab7640" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [win]

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - numpy
    - sympy

test:
  imports:
    - rt1

about:
  home: http://github.com/pygeo/rt1
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Bistatic first order radiative transfer model'

  description: |
    RT1 is a bistatic general first order radiative transfer models. More details in the documentation. 
  doc_url: http://rt1.readthedocs.io/
  dev_url: https://github.com/pygeo/rt1

extra:
  recipe-maintainers:
    - bulli92
