travis:
  secure:
    BINSTAR_TOKEN: KSPHOkVX7kH+5GbRgOneR9+eUAjN2xpEbVdPrVuDnsGtjhn609anerS39ry9gCAWnd/jGTS0/qrfWt+DNKTNrG7HqdmLm+DdAngfdQ9VrAwbzGjS/Xnuyi3B1cdv0yAsg04HbMk8HTlYb5Gf4/jumu/i5iDd0otQCMBDN567ONI3eJRQyyD7dw7VY1VY8bBlIo9t92cmXfz1tKhHHODnj7fLnJqqwD3TYS48Ow3+2yaqU0UX4mjDECD74QQ7tbVyiQmWxVlcylEqvGnr7tHRCsehxA7nYm4xAdTQs+Dktq8btSPxxvvJqFpTwMTLmHNAiRIU67LTvH5abx5jP0AEEKVQZXucWtfiOxwf8L7hnpQReWfUbl3RVTomws26TPC3Dv+Hfbjzz8O00Z1U/5wtIB7vJfjsdoLZ2u0WHqCQX7m6tcifXEcsf5R+7v2YovPx4NlApG5rkunhHUegaPN3xcyYFW6JNHO2nPiXt3wQXWf4V+dI1PJO6eiB8nbYLFWdveyyCRJ5v2M1oRqBs15fISOyd6hlD+4PR6c4ZAwdFsnLEfSXGcZdzEBJ5lCJYOAZG7Sg/KGfyR9N/KvGk4rR+Nmsh3rxkINK+fGGItfzULAT3MKRdQOXd6r1D+B6f3jgbFKl6T9n/VJswFn60XLDP8bfDat9AdDIWA9rtKV/uNM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
